# Generated by Django 4.2.16 on 2025-01-02 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='users',
            field=models.ManyToManyField(related_name='purchased_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
